# Generated by Django 4.1.1 on 2022-09-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, null=True)),
                ('telefonos', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_cobro', models.DateField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cabecera',
                'verbose_name_plural': 'Cabeceras',
                'ordering': ('-fecha', 'nombre'),
            },
        ),
    ]
