# Generated by Django 4.1.1 on 2022-09-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabecera',
            name='deuda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Costo'),
        ),
        migrations.AddField(
            model_name='cabecera',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
