# Generated by Django 4.1.1 on 2022-09-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0002_cabecera_deuda_cabecera_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabecera',
            options={'ordering': ('nombre',), 'verbose_name': 'Cabecera', 'verbose_name_plural': 'Cabeceras'},
        ),
        migrations.RemoveField(
            model_name='cabecera',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cabecera',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='cabecera',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='cabecera',
            name='telefonos',
        ),
        migrations.AlterField(
            model_name='cabecera',
            name='deuda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Deuda'),
        ),
    ]
