# Generated by Django 4.1.1 on 2022-09-22 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0004_pagodeuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagodeuda',
            name='abono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Abono'),
        ),
        migrations.AlterField(
            model_name='pagodeuda',
            name='fecha_ab',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
