# Generated by Django 4.1.1 on 2022-09-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0007_remove_cabecera_estado_alter_pagodeuda_abono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabecera',
            name='deuda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Deuda'),
        ),
    ]
