# Generated by Django 4.1.1 on 2022-09-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0008_alter_cabecera_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabecera',
            name='meses_a_diferir',
            field=models.CharField(choices=[(1, '3 meses'), (2, '6 meses'), (3, '9 meses'), (4, '12 meses'), (5, '24 meses')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='cabecera',
            name='deuda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Deuda'),
        ),
    ]
