# Generated by Django 4.1.1 on 2022-09-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0009_cabecera_meses_a_diferir_alter_cabecera_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabecera',
            name='cuota_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Cuota Mensual'),
        ),
        migrations.AlterField(
            model_name='cabecera',
            name='deuda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto a diferir'),
        ),
    ]
