# Generated by Django 4.1.1 on 2022-09-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0011_alter_cabecera_meses_a_diferir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabecera',
            name='meses_a_diferir',
            field=models.CharField(choices=[('3 meses', '3 meses'), ('6 meses', '6 meses'), ('9 meses', '9 meses'), ('12 meses', '12 meses'), ('24 meses', '5 meses')], default='Seleccione el mes', max_length=200),
        ),
    ]
