# Generated by Django 4.1.1 on 2022-09-22 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0012_alter_cabecera_meses_a_diferir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabecera',
            name='meses_a_diferir',
            field=models.CharField(choices=[('3 meses', '3 meses'), ('6 meses', '6 meses'), ('9 meses', '9 meses'), ('12 meses', '12 meses'), ('24 meses', '24 meses')], default='3 meses', max_length=200),
        ),
        migrations.AlterField(
            model_name='pagodeuda',
            name='deuda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuenta_cobrar.cabecera'),
        ),
    ]
