# Generated by Django 4.1.1 on 2022-09-22 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0013_alter_cabecera_meses_a_diferir_alter_pagodeuda_deuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagodeuda',
            name='abono',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='pagodeuda',
            name='deuda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuenta_cobrar.cabecera'),
        ),
    ]
