# Generated by Django 4.1.1 on 2022-09-23 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0014_alter_pagodeuda_abono_alter_pagodeuda_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagodeuda',
            name='cabecera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuenta_cobrar.cabecera'),
        ),
        migrations.AlterField(
            model_name='pagodeuda',
            name='deuda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Deuda'),
        ),
    ]
