# Generated by Django 4.1.1 on 2022-09-23 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0015_pagodeuda_cabecera_alter_pagodeuda_deuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagodeuda',
            name='cabecera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab', to='cuenta_cobrar.cabecera', verbose_name='Cliente'),
        ),
    ]
