# Generated by Django 4.1.1 on 2022-09-23 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0016_alter_pagodeuda_cabecera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabecera',
            name='fecha_cobro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
