# Generated by Django 4.1.1 on 2022-09-23 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0017_alter_cabecera_fecha_cobro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagodeuda',
            name='cabecera',
            field=models.ForeignKey(blank=True, default='Seleccionar', null=True, on_delete=django.db.models.deletion.CASCADE, to='cuenta_cobrar.cabecera', verbose_name='Cliente'),
        ),
    ]
