# Generated by Django 4.1.1 on 2022-09-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0020_alter_cabecera_meses_a_diferir'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabecera',
            name='saldo_interes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Saldo (+10% interés)'),
        ),
    ]
