# Generated by Django 4.1.1 on 2022-09-27 06:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0022_alter_cabecera_saldo_interes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, null=True)),
                ('telefonos', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cabecera',
            name='fecha_cobro',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha inicio cobro'),
        ),
        migrations.AlterField(
            model_name='cabecera',
            name='saldo_interes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Deuda'),
        ),
        migrations.AlterField(
            model_name='cabecera',
            name='nombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuenta_cobrar.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pagodeuda',
            name='cabecera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuenta_cobrar.cliente', verbose_name='Cliente'),
        ),
    ]
