# Generated by Django 4.1.1 on 2022-09-28 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0024_remove_cliente_estado_alter_cliente_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='genero',
        ),
    ]
